# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IMPRESSION-ESM
email: romain.roehrig@meteo.fr
description: > # this means to ignore newlines until "baseurl:"
  Improving the physical process representation in Earth system models
baseurl: "" # the subpath of your site, e.g. /blog
url: http://TRACCS-PC7-IMPRESSION-ESM.github.io/
github_username:  TRACCS-PC7-IMPRESSION-ESM

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
